---
title: "Research"
---

This is a list of some of my projects undertaken with fellow researchers-in-training.  
<br>



## COVID-19 in India: Unpacking the second-wave secondhand

##### *with Kritarth Jha, Avantika Prabhakar, Vasanthi Swetha*
During the second-wave of the COVID-19 pandemic, India was hit with a devastating public health crisis, with the hospitals hitting capacity constraints and the state machinery reeling under unpreparedness. We, a group of development economics RAs with our strong networks of field surveyors in India, started [Co-verifed](https://vasanthiswetha.wixsite.com/coverified) with the aim of verifying medical resources daily in two of the worst hit Indian states, Bihar & Jharkhand. Alongside, we conducted phone surveys with the local level administrations (village leaders and maternal health workers) and doctors when vaccines started being deployed towards the end of the second wave. Our surveys were aimed at collecting information on covid testing, vaccine hesitancy, availability of medical resources, and some other issues around unemployment and migration. We also conducted in-depth qualitative interviews with maternal health workers (anganwadi sevikas) on vaccine hesitancy. 
We are hoping to complete the analysis and make the report and data public soon, albeit carving out time from our full time jobs has made this slower than we would like! Meanwhile, I'll share this short [thread](https://twitter.com/kritarthjha/status/1399276609924861959) with you that we had put together on some quick learnings about vaccine hesitancy in Bihar. 
<br>


## Assuring 'Half the Sky': Evaluation of Bihar Police Reforms
##### *with Mridul Joshi, Mohnish Kedia, Sayan Kundu, Jayanti Singh*

This project aims to evaluate Model Police Stations and All-Women Police Stations to understand its effect on women’s perception of the police force in the Indian state of Bihar. Credibility of a state agent is crucial in their ability to implement state policies and has been identified as a key bottleneck in development economics literature. We evaluate the impact of a novel policy change that improves infrastructural and technological hiatus prevalent in traditional police stations across the state, incorporates soft-skills training programs, and increases the presence of female police officers, on service take-up by women and changes in their perception brought about by institutions. We exploit the geographical variation in policy implementation and use neighbouring jurisdictions in the same district as counterfactuals to the treatment jurisdictions which were mostly in district police headquarters. Using a difference-in-difference strategy, we find small but significant improvement in women’s perception of police services, and we postulate the effect is driven by the people friendly approach adopted by these new generation police stations along with the improved infrastructure that the government has aimed to provide. The data collection for this project was supported by a public research grant and the resulting report was submitted to the Government of Bihar.



